-- 1.	Copy the order by exercise and save it as functions_exercises.sql.
-- 2.	Write a query to to find all employees whose last name starts and ends with 'E'. Use concat() to combine their first and last name together as a single column named full_name.
-- 3.	Convert the names produced in your last query to all uppercase.
-- 4.	Find all employees hired in the 90s and born on Christmas. Use datediff() function to find how many days they have been working at the company (Hint: You will also need to use NOW() or CURDATE()),
-- 5.	Find the smallest and largest current salary from the salaries table.
-- 6.	Use your knowledge of built in SQL functions to generate a username for all of the employees. A username should be all lowercase, and consist of the first character of the employees first name, the first 4 characters of the employees last name, an underscore, the month the employee was born, and the last two digits of the year that they were born. Below is an example of what the first 10 rows will look like:
